name: DayGlo Photography
favicon: null
layout_spectrum: 0.491
typography_spectrum: 0.42882
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#717372'
    - '#ededed'
    - '#090907'
    - '#282947'
    - '#c6c6c6'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
