typography_spectrum: 0.42882
color:
  brandColors:
    - '#010101'
    - '#2a3547'
    - '#76808c'
    - '#c0c0c0'
    - '#fff7d2'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.76674
analytics:
  google: null
  facebook: null
  twitter: null
name: DayGlo Photography
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Welcome
purpose: []
