name: DayGlo Photography
favicon: null
layout_spectrum: 1
typography_spectrum: 0.42882
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060604'
    - '#92b8e5'
    - '#232b3e'
    - '#647c96'
    - '#3a4e69'
  brandStrength: 0.5
  lightness: 0.375
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
